config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homepage#index'

  # Explore page
  namespace :data do
    resources :explore, only: [:index, :show]
  end

  # Countries dashboard
  resources :countries, only: [:index, :show]

  # Insights
  resources :insights, only: [:index]

  # Insights
  resources :partners, only: [:index]

  # Planet pulse
  get '/data/pulse', to: 'planet_pulse#index', as: 'planet_pulse'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"] if Rails.env == 'production'
  before_action :site_name, :set_fitscreen

  private

    def site_name
      @site_name = 'Resource Watch'
    end

    def set_fitscreen
      pages_fitscreen = ['explore', 'planet_pulse']
      @is_fitscreen = pages_fitscreen.include?(controller_name)
    end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @title = t 'titles.dashboards'
  end

  def show
    @countrySlug = params["id"]
  end
end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  def index
    @title = t 'titles.explore'
  end

  def show
    @exploreSlug = params["id"]
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/insights_controller.rb
class InsightsController < ApplicationController
  def index
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  def index
    @partners = [
      {name:'wri', image:'partners/wri@2x.png', url:'partners/wri', description: "The World Resources Institute (WRI) is a global research organization that spans more than 50 countries. We convene over 450 experts to work closely with leaders to turn big ideas into actions that sustain our natural resources—the foundation of economic opportunity and human well-being."},
      {name:'vizzuality', image:'partners/vizzuality@2x.png', url:'partners/vizzuality', description: "Vizzuality is a world-renowned digital agency, delivering bespoke, beautiful visualisations and tools to the most important organisations in the world. Pushing the boundaries of how data is stored, shared and visualised, we help to improve our world one visualisation at a time."},
      {name:'google', image:'partners/google@2x.png', url:'partners/google', description: "Google Earth Engine brings together the world's satellite imagery and makes it available online alongside tools for scientists, independent researchers and nations to mine this massive warehouse of data.", disabled: true},
      {name:'cartodb', image:'partners/cartodb@2x.png', url:'partners/cartodb', description: "The easiest way to make maps online. Since launching in 2012 over 130,000 people have used it to create data-driven maps, which enable visual discovery of trends and patterns, and make better, faster decisions.", disabled: true},
      {name:'digitalglobe', image:'partners/digitalglobe@2x.png', url:'partners/digitalglobe', description: "DigitalGlobe is a leading provider of high‑resolution Earth imagery products and services. Sourced from our own advanced satellite constellation, our imagery solutions support a wide variety of uses, including environmental monitoring.", disabled: true},
      {name:'earthgenome', image:'partners/earthgenome@2x.png', url:'partners/earthgenome', description: "The Earth Genome is enabling the world's key institutions to fully account for natural capital in all their decisions. We are connecting the world's best earth data, scientists, and technology providers to drive insight and innovation for governments, NGOs, corporations, and investors.", disabled: true},
      {name:'descarteslabs', image:'partners/descarteslabs@2x.png', url:'partners/descarteslabs', description: "Our mission is to better understand planet Earth by analyzing massive amounts of imagery. We’ll begin this journey by understanding satellite imagery to enable real-time global awareness — whether it’s food production, energy infrastructure, the growth of cities, or our impact on the environment. Not only will we identify what’s in a single image, but we’ll also be looking at how our Earth changes over time.", disabled: true}
    ]
  end
end

app/controllers/planet_pulse_controller.rb
class PlanetPulseController < ApplicationController
  def index
    @content_class = '-dark'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page_class?(path)
    return '-active' if request.path == path
    ''
  end
end

app/views/countries/index.html.erb
<% breadcrumb :countries %>

<div class="row">
  <div class="col -xs-12">
    <header class="main-header">
      <h1><%= t('countries.title') %></h1>
      <a id="fullscreenBtn" class="link fullscreen-btn" href="#">
        <%= t('fullscreen.set') %>
      </a>
    </header>
    <%= form_tag nil, id: 'searchForm' do %>
      <div class="input-group">
        <%= search_field_tag :q, nil, placeholder: t('datasets.search') %>
        <%= submit_tag t('search') %>
      </div>
    <% end %>
    <div id="countries"></div>
  </div>
</div>

app/views/countries/show.html.erb
<% breadcrumb :country, @countrySlug %>

<div class="row">
  <div class="col -xs-12">
    <div id="dashboard">
    </div>
  </div>
</div>

app/views/explore/index.html.erb
<% breadcrumb :explore %>

<div class="rw-explore-content">
  <div class="rw-explore-mobile-nav">
    <button class="action -plain back js-go-to-explore">< Go to the explore</button>
    <button class="action -plain js-go-to-map">Go to the map ></button>
  </div>
  <div id="exploreContent" class="row -expanded">
    <div class="col -xs-12 -sm-12 -md-7 -lg-7 rw-explore">
      <%= breadcrumbs %>

      <h1><%= t('titles.explore') %></h1>
      <%= form_tag nil, id: 'searchForm' do %>
        <div class="input-group">
          <%= search_field_tag :q, nil, placeholder: 'Search datasets' %>
          <%= submit_tag "Search" %>
        </div>
      <% end %>
      <div id="exploreNavigation"></div>
      <div id="exploreDashboard"></div>
      <div id="pagination"></div>
    </div>
  </div>

  <div class="rw-explore-map">
    <div id="mapToggle" class="rw-map-toggle">
      <svg class="rw-icon rw-icon-arrow">
        <use xlink:href="#icon-arrow"></use>
      </svg>
    </div>
    <div id="legend"></div>
    <div id="map" class="-dark"></div>
  </div>
</div>

app/views/explore/show.html.erb
<% breadcrumb :explore_detail, @exploreSlug %>

<div class="rw-explore-content">
  <div id="mainContent" class="row -expanded _is-content-loading">
    <div class="main-content">
      <div class="col -sm-12 -md-7 rw-explore">
        <div class="row">
          <%= breadcrumbs %>

          <div id="cardDetail"></div>

          <div class="col -xs-12">
            <h2 class="-pink">Similar datasets</h2>
            <div id="exploreDashboard"></div>
            <div id="pagination"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="rw-explore-map">
    <div id="mapToggle" class="rw-map-toggle">
      <svg class="rw-icon rw-icon-arrow">
        <use xlink:href="#icon-arrow"></use>
      </svg>
    </div>
    <div id="legend"></div>
    <div id="map" class="-dark"></div>
  </div>
</div>

app/views/homepage/index.html.erb
<% breadcrumb :root %>
<div class="rw-l-banner">
  <%= render "shared/featured_insight_banner" %>
</div>
<div class="row">
  <div class="col -xs-12">
    <section class="rw-l-section">
      <header class="header -col">
        <h2 class="title">Latest Insights</h2>
        <p>Read the latest stories, findings and analysis from our community</p>
      </header>

      <%= render "shared/insights" %>

      <button class="action -gray">
        <%= link_to page_path('insights'), class:'link' do %>
          <%= t('insights.explore') %>
        <% end %>
      </button>
    </section>
  </div>
</div>

<%= render "shared/planet_pulse" %>

<div class="row">
  <div class="col -xs-12">
    <section class="rw-l-section">
      <%= render "shared/explore_dashboard" %>
    </section>
  </div>
</div>

<!-- Provisional images -->
<div class="row">
  <div class="col -xs-12">
    <section class="rw-l-section">
      <header class="header -col">
        <h2 class="title">Get involved</h2>
      </header>

      <%= image_tag "get_involved.png", class: 'image' %>
    </section>
  </div>
</div>

<div class="row -last">
  <div class="col -xs-12">
    <section class="rw-l-section">
      <header class="header -col">
        <h2 class="title">Social Media</h2>
      </header>

      <%= image_tag "social.png", class: 'image' %>
    </section>
  </div>
</div>

<%= image_tag "apps.png", class: 'image' %>

app/views/insights/index.html.erb
<% breadcrumb :insights %>

<div class="row">
  <div class="col -xs-12">
    <h1><%= t('insights.title') %></h1>
  </div>
</div>


<div class="row">
  <div class="col -xs-12">
    <section class="rw-l-section">
      <%= render "shared/insights" %>
    </section>
  </div>
</div>


<div class="row">
  <div class="col -xs-12">
    <section class="rw-l-section -cut">
      <%= render "shared/planet_pulse" %>
    </section>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title><%= @title ? @title + ' | ' : nil %><%= @site_name %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato:400,300,700" %>
    <%= stylesheet_link_tag "https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/3.15/themes/css/cartodb.css", media: "all" %>
    <%= stylesheet_link_tag "application", media: "all" %>
  </head>
  <body class="-<%= controller_name %> <%= '-fitscreen' if @is_fitscreen %>">
    <%= render "shared/symbol-defs" %>
    <%= render "shared/header" %>
    <div id="content" class="l-main <%= @content_class if defined?(@content_class) %>">
      <%= render "shared/breadcrumbs", controller: params[:controller] %>
      <%= yield %>
    </div>
    <%= render "shared/footer" unless @is_fitscreen %>
    <%= javascript_include_tag "https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/3.15/cartodb.js" %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title><%= @title ? @title + ' | ' : nil %><%= @site_name %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato:400,300,700" %>
    <%= stylesheet_link_tag "application", media: "all" %>
  </head>
  <body class="-<%= controller_name %> <%= '-fitscreen' if @is_fitscreen %>">
    <%= render "shared/symbol-defs" %>
    <%= render "shared/header" %>
    <div class="l-main -static">
      <%= yield %>
    </div>
    <%= render "shared/footer" unless @is_fitscreen %>
    <%= javascript_include_tag "static" %>
  </body>
</html>

app/views/pages/partners/vizzuality.html.erb
<div class="rw-partners">
  <div class="partners-hero is-partners-vizzuality">
    <div class="row">
      <div class="col -xs-12">
        <p class="partners-hero-subtitle">Resource Watch Partner</p>
        <h2 class="partners-hero-logo"><img src="https://vizzuality.github.io/WRW-Prototype/img/partner-vizzuality-logo.png"></h2>
        <div class="partners-hero-description">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
            commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
            commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/partners/wri.html.erb
<div class="rw-partners">
  <div class="partners-hero is-partners-wri">
    <div class="row">
      <div class="col -xs-12">
        <p class="partners-hero-subtitle">Resource Watch Partner</p>
        <h2 class="partners-hero-logo"><img src="https://vizzuality.github.io/WRW-Prototype/img/partner-wri-logo.png"></h2>
        <div class="partners-hero-description">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
            commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
            commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/privacy.html.erb
<div class="row">
  <div class="col -xs-12">
    <h1><%= t('titles.privacy') %></h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem recusandae accusamus illum, modi molestias sunt ratione quam assumenda inventore iste similique consequuntur asperiores aliquam aperiam sapiente fugit, cumque a non!</p>
  </div>
</div>

app/views/pages/terms.html.erb
<div class="row">
  <div class="col -xs-12">
    <h1><%= t('titles.terms') %></h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem recusandae accusamus illum, modi molestias sunt ratione quam assumenda inventore iste similique consequuntur asperiores aliquam aperiam sapiente fugit, cumque a non!</p>
  </div>
</div>

app/views/partners/index.html.erb
<% breadcrumb :partners %>

<div class="rw-partners">

<div class="row">
  <div class="col -xs-12">
      <h1><%= t('titles.partners') %></h1>
  </div>
</div>

<div class="partners-intro">
  <div class="row">
    <div class="col -xs-12">
      <h3>We have a massive opportunity
        <br>
        to build a sustainable society
      </h3>
      <p>
        We cannot undertake this endeavour alone. Resource Watch requires leading experts to work across data collection, processing, storage and visualisation. To achieve our ambitious goals we want to gather the top minds from around the world and work at
        pace, to complete our work before it’s too late.<br>Just take a look at who we’ve got joining us on the journey already!<br>If you see yourself as part of this team, just get in touch!
      </p>
    </div>
  </div>
</div>

  <div class="row">
    <div class="col -xs-12">
      <%= render "shared/partners", partners: @partners%>
    </div>
  </div>


  <div class="row">
    <div class="col -xs-12">
      <section class="rw-l-section">
        <%= render "shared/contact" %>
      </section>
    </div>
  </div>
</div>

app/views/planet_pulse/index.html.erb
<div id="globeView" class="globe -loading"></div>
<div id="planetPulsesView"></div>

app/views/shared/_breadcrumbs.html.erb
<% if controller != "explore" %>
  <div class="row">
    <div class="col-xs-12">
      <%= breadcrumbs %>
    </div>
  </div>
<% end %>

app/views/shared/_contact.html.erb
<div id="rw-contact" class="rw-banner">
  <a href="" class="modal-signup">
    <%= image_tag 'https://vizzuality.github.io/WRW-Prototype/img/banner-3.jpg', class:"image" %>
  </a>
  <h3 class="header"><%= t('contact.header') %></h3>
  <a href="mailto:resourcewatch@wri.org" class="button -large modal-signup"><%= t('contact.link') %></a>
</div>

app/views/shared/_country_dashboard.html.erb
<section>
  <div class="rw-country-dashboard-selector js-country-dashboard-selector">
      <header>
        <h2><%= t('dashboard') %></h2>
        <p><%= t('countries.header') %></p>
      </header>
      <div class="country-selector select-countries-dropdown dropdown-index">
        <select>
          <option value="" disabled="true" selected="true"><%= t('countries.choose') %></option>
        </select>
        <!-- <button type="submit"><%= t('lets_go') %></button> -->
      </div>
  </div>
</section>

app/views/shared/_explore_dashboard.html.erb
<section class="rw-l-section">
  <header class="header -col">
    <h2 class="title"><%= t('explore.header') %></h2>
    <p>Explore the data, create visualizations, and tell the world your story</p>
  </header>
  <%= render "shared/country_dashboard" %>
  <h4 class="subtitle">Latest</h4>
  <div id="latestDashboard" class="cards _minh"></div>

  <h4 class="subtitle">Popular</h4>
  <div id="popularDashboard" class="cards _minh"></div>

  <button class="action -gray -no-mg">
    <%= link_to data_explore_index_path, class:'link' do %>
      <%= t('explore.button') %>
    <% end %>
  </button>
</section>

app/views/shared/_featured_insight_banner.html.erb
<section class="rw-hero" style="background-image: url(<%= image_path 'banners/interactive-planet.jpg' %>)">
  <div class="ticker">
    <div class="provisional-updates"></div>
  </div>
  <div class="row">
    <div class="col -xs-12 rw-hero-content">
      <div class="title -center">
        <%= link_to 'Quick and easy access to a world of data', page_path('insights/interactive-edi') %>
        <p class="desc">Explore the latest data, make insights, and help build a more sustainable planet</p>
      </div>
    </div>
  </div>
  <div class="footer">
    <svg class="icon icon-travel_world -first"><use xlink:href="#icon-travel_world"></use></svg>
    <p>Dive into Resource Watch findings</p>
    <%= link_to page_path('planet-pulse'), class:'link' do %>
      Explore the planet
    <% end %>
  </div>
</section>

app/views/shared/_footer.html.erb
<footer class="rw-l-footer">

  <div class="rw-footer-separator">
    <h3><%= link_to t('titles.partners'), page_path('partners') %></h3>
  </div>

  <div class="row">
    <div class="col -xs-12">
      <ul class="rw-footer-carousel js-footer-carousel -invisible">
        <li><a href="#" title="CartoDB"><%= image_tag "partners/cartodb@2x.png", alt: "CartoDB", height: "27px", width: "105px" %></a></li>
        <li><a href="#" title="Danish International Development Agency"><%= image_tag "partners/danida.png", alt: "Danish International Development Agency", height: "20px", width: "140px" %></a></li>
        <li><a href="#" title="Descartes Labs"><%= image_tag "partners/descarteslabs@2x.png", alt: "Descartes Labs", height: "32px", width: "106px" %></a></li>
        <li><a href="#" title="Astro Digital"><%= image_tag "partners/astrodigital@2x.png", alt: "Astro Digital", height: "45px", width: "102px" %></a></li>
        <li><a href="#" title="DigitalGlobe"><%= image_tag "partners/digitalglobe@2x.png", alt: "DigitalGlobe", height: "30px", width: "141px" %></a></li>
        <li><a href="#" title="The Earth Genome"><%= image_tag "partners/earthgenome@2x.png", alt: "The Earth Genome", height: "37px", width: "94px" %></a></li>
        <li><a href="#" title="Ecosystems Services for Poverty Alleviation"><%= image_tag "partners/espa.png", alt: "Ecosystems Services for Poverty Alleviation", height: "25px", width: "94px" %></a></li>
        <li><a href="#" title="esri"><%= image_tag "partners/esri.png", alt: "esri", height: "29px", width: "80px" %></a></li>
        <li><a href="#" title="Global Partnership"><%= image_tag "partners/globalpartnership.png", alt: "Global Partnership", height: "29px", width: "100px" %></a></li>
        <li><a href="#" title="Google"><%= image_tag "partners/google@2x.png", alt: "Google", height: "28px", width: "86px" %></a></li>
        <li><a href="#" title="The North American Electric Reliability Corporation"><%= image_tag "partners/nerc.png", alt: "The North American Electric Reliability Corporation", height: "33px", width: "45px" %></a></li>
        <li><a href="#" title="Ministry of Foreign Affairs of the Netherlands"><%= image_tag "partners/netherlands.png", alt: "Ministry of Foreign Affairs of the Netherlands", height: "53px", width: "128px" %></a></li>
        <li><a href="#" title="Research into Results"><%= image_tag "partners/researchintoresults.png", alt: "Research into Results", height: "40px", width: "65px" %></a></li>
        <li><a href="#" title="Swedish International Development Cooperation Agency"><%= image_tag "partners/sida.png", alt: "Swedish International Development Cooperation Agency", height: "39px", width: "77px" %></a></li>
        <li><a href="#" title="Tilia Fund"><%= image_tag "partners/tilia.png", alt: "Tilia Fund", height: "33px", width: "48px" %></a></li>
        <li><a href="#" title="University of Maryland"><%= image_tag "partners/umd@2x.png", alt: "University of Maryland", height: "44px", width: "45px" %></a></li>
        <li><a href="#" title="United Nations Development Programme"><%= image_tag "partners/undp.png", alt: "United Nations Development Programme", height: "54px", width: "27px" %></a></li>
        <li><a href="#" title="United Nations Environment Programme"><%= image_tag "partners/unep@2x.png", alt: "United Nations Environment Programme", height: "51px", width: "45px" %></a></li>
        <li><a href="#" title="University of Edinburgh"><%= image_tag "partners/uniedim.png", alt: "University of Edinburgh", height: "49px", width: "48px" %></a></li>
        <li><a href="#" title="Vizzuality"><%= image_tag "partners/vizzuality@2x.png", alt: "Vizzuality", height: "25px", width: "98px" %></a></li>
        <li><a href="#" title="World Resources Institute"><%= image_tag "partners/wri@2x.png", alt: "World Resources Institute", height: "42px", width: "119px" %></a></li>
      </ul>
    </div>
  </div>

  <%# Footer top %>
  <div class="rw-l-top-footer">
    <div class="row">
      <div class="col -xs-6 -md-1 rw-footer-logo">
        <svg class="rw-icon rw-icon-symbol-grey">
          <use xlink:href="#icon-symbol-grey"></use>
        </svg>
      </div>
      <div class="col -xs-6 -md-11">
        <%# Footer navigation %>
        <ul class="rw-footer-nav">
          <li>
            <%= link_to t('titles.insights'), insights_path %>
            <ul>
              <li><a href="#">Recent insights</a></li>
              <li><a href="#">Highlighted insights</a></li>
            </ul>
          </li>

          <li>
            <a href="/about">About</a>
            <ul>
              <li><%= link_to 'Partners', '/about/partners' %></li>
            </ul>
          </li>

          <li>
            <%= link_to 'Data', '/data' %>
            <ul>
              <li><a href="/data/explore">Explore datasets</a></li>
              <li><a href="/data/dashboards">Dashboards</a></li>
            </ul>
          </li>

          <li>
            <a href="/get-involved"><%= t('get_involved') %></a>
            <ul>
              <li><a href="#">Submit an insight</a></li>
              <li><a href="#">Contibute data</a></li>
              <li><a href="#">Join community</a></li>
            </ul>
          </li>

        </ul>
      </div>
    </div>
  </div>

  <%# Footer bottom %>
  <div class="rw-l-bottom-footer">
    <div class="row">
      <div class="col -xs-12 -sm-6">
        <%# Bottom navigation %>
        <ul class="rw-bottom-nav">
          <li><%= link_to t('titles.terms'), '#' %></li>
          <li>-</li>
          <li><%= link_to t('titles.privacy'), '#' %></li>
        </ul>
      </div>
      <div class="col -xs-12 -sm-6">
        <%# Copy %>
        <p class="rw-copy">© <%= Time.now.strftime('%Y') %> - <%= @site_name %></p>
      </div>
    </div>
  </div>

</footer>

app/views/shared/_header.html.erb
<header id="header" class="rw-l-header">

  <%# Header top %>
  <!-- <div class="rw-l-top-header">
    <div class="row">
      <div class="col -xs-12 -sm-6 -sm-offset-6">
        <%# Language navigation %>
        <div class="rw-header-lang js-header-lang-menu">
          <%= t('languages.english') %>
          <ul class="rw-lang-nav -hidden js-nav">
            <li><%= t('languages.english') %></li>
            <li><%= t('languages.french') %></li>
            <li><%= t('languages.deutsche') %></li>
          </ul>
        </div>
      </div>
    </div>
  </div> -->

  <%# Header navigation bar %>
  <div class="rw-l-nav-header -vcenter">
    <div class="row -vcenter">
      <div class="col -xs-12 -md-4 rw-top-nav">
        <%# Brand zone %>
        <%= link_to root_path, class: "rw-brand" do %>
          <svg class="rw-icon rw-icon-logo">
            <use xlink:href="#icon-logo"></use>
          </svg>
        <% end %>
        <div class="rw-menu-btn">
          <button type="button"> Menu </button>
        </div>
      </div>
      <div class="col -xs-12 -md-8">
        <%# Main navigation %>
        <nav class="rw-main-nav">
          <ul>
            <li class="-dropdown -white js-dropdown">
              Data
              <div class="dropdown">
                <ul class="list">
                  <li ><%= link_to t('titles.all_data'), data_explore_index_path, class: active_page_class?(data_explore_index_path) %></li>
                  <li ><%= link_to 'Dashboards', '/data/dashboards' %></li>
                  <li ><%= link_to t('titles.planet_pulse'), planet_pulse_path, class: active_page_class?(planet_pulse_path) %></li>
                </ul>
              </div>
            </li>
            <li ><%= link_to t('titles.insights'), page_path('insights'), class: active_page_class?(page_path('insights')) %></li>
            <li class="-dropdown -white js-dropdown">
              <%# link_to t('titles.about'), '/about' %> About
              <div class="dropdown">
                <ul class="list">
                  <li ><%= link_to t('titles.partners'), partners_path, class: active_page_class?(partners_path) %></li>
                </ul>
              </div>
            </li>
            <li>
              <%= link_to t('get_involved'), '/get-involved' %>
            </li>
            <li>
              <%= link_to t('login'), '/login' %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>

</header>

app/views/shared/_partners.html.erb
<div class="partners-cards">
  <% @partners.each do |p| %>
    <%= content_tag(:div, :class =>  p[:disabled] ? "partner-card is-disabled" : 'partner-card') do %>

      <%= link_to page_path(p[:url]) do %>
        <%= image_tag p[:image] %>
      <% end %>

      <p><%= p[:description] %></p>

      <%= link_to page_path(p[:url]) do %>
        <%= t('read_more') %>
      <% end %>

    <% end %>
  <% end %>
</div>

app/views/shared/_planet_pulse.html.erb
<section class="rw-l-section">
  <div class="rw-banner -bg" style="background-image: url(<%= image_path "planetpulse.png" %>)">

    <div class="row">
      <div class="col -xs-6">
        <h3 class="header">Take the pulse of our planet</h3>
        <h4 class="tab">Planet Pulse</h4>
        <p class="desc">A global snapshot of key impacts on livelihoods from the latest data.</p>
        <div class="btn"><%= link_to t('planet_pulse.launch'), planet_pulse_path, class: 'button -large' %></div>
      </div>
    </div>
  </div>
</section>